Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -29,6 +29,18 @@ jobs:
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: 8.0.x
+          
+      - name: Remove existing NuGet source
+        run: dotnet nuget remove source github || echo "Source not found, skipping removal"
+      
+      - name: Configure NuGet credentials
+        run: |
+          dotnet nuget add source "https://nuget.pkg.github.com/caiofabiogomes/index.json" \
+            --name github \
+            --username ErickGoldberg \
+            --password ${{ secrets.SECRET_NUGET_PACKAGES }} \
+            --store-password-in-clear-text
+
 
       - name: Restore and Build
         run: |
@@ -48,7 +60,7 @@ jobs:
       - name: Build and Push Docker Image (Only Release)
         if: matrix.configuration == 'Release'
         run: |
-          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
+          docker build --build-arg ARG_SECRET_NUGET_PACKAGES=${{ secrets.SECRET_NUGET_PACKAGES }} -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
           docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest
           docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
           docker push ${{ env.IMAGE_NAME }}:latest
